/**
 * Security & Input Sanitization Suite for NOVA Player
 * Protects against XSS, Prototype Pollution, Memory Injection, and Path Traversal.
 */

/**
 * Sanitizes arbitrary user strings (titles, playlist names, search inputs).
 * Strips HTML tags, removes ASCII control characters, and caps maximum length.
 */
export function sanitizeText(input: unknown, maxLength = 120): string {
  if (typeof input !== 'string') {
    return '';
  }

  return input
    // Remove null bytes and ASCII control characters (0-31, except normal space)
    .replace(/[\x00-\x1F\x7F]/g, '')
    // Strip HTML tag structures (<...>) to prevent XSS
    .replace(/<[^>]*>?/gm, '')
    // Trim extra surrounding whitespace
    .trim()
    // Slice to maximum allowed characters to prevent memory/buffer overload
    .slice(0, maxLength);
}

/**
 * Validates and sanitizes media and image URLs.
 * Strictly permits safe schemes: http:, https:, blob:, and data:image/.
 * Rejects javascript:, data:text/html, vbscript: or arbitrary schemes.
 */
export function sanitizeMediaUrl(url: unknown): string {
  if (typeof url !== 'string' || !url) {
    return '';
  }

  const trimmed = url.trim();

  // 1. Allow standard blob URLs generated by browser for local files
  if (trimmed.startsWith('blob:')) {
    return trimmed;
  }

  // 2. Allow base64 image data URIs (APIC cover art)
  if (trimmed.startsWith('data:image/')) {
    return trimmed;
  }

  // 3. Allow valid HTTP / HTTPS web URLs
  if (/^https?:\/\//i.test(trimmed)) {
    try {
      const parsed = new URL(trimmed);
      if (parsed.protocol === 'http:' || parsed.protocol === 'https:') {
        return parsed.href;
      }
    } catch {
      return '';
    }
  }

  // 4. Allow CSS gradients (used as fallback cover arts)
  if (trimmed.startsWith('linear-gradient(') || trimmed.startsWith('radial-gradient(')) {
    // Verify no script or url injection inside gradient string
    if (!trimmed.includes('url(') && !trimmed.includes('<') && !trimmed.includes('>')) {
      return trimmed;
    }
  }

  return '';
}

/**
 * Prevents directory traversal attacks by removing relative path characters.
 */
export function sanitizeFilePath(filePath: string): string {
  return filePath
    .replace(/\.\./g, '')
    .replace(/[\0\x00-\x1F\x7F]/g, '')
    .replace(/\\+/g, '/');
}
